name: Release publisher
on:
  push:
    tags:
    - 'v*'
env:
  GO111MODULE: on

jobs:
  publish_release:
    name: Publish multiwerf release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout code
      uses: actions/checkout@v1
    - name: Publish
      run: |
        echo DISABLED ./scripts/publish_release.sh --tag ${GITHUB_REF#refs/tags/}
      shell: bash
      env:
        PUBLISH_BINTRAY_AUTH: ${{ secrets.PUBLISH_BINTRAY_AUTH }}
        PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
